[package]
name = "rust-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
bincode = "1.3"

[features]
default = []
load-magic = []